In [25]:
import numpy as np
import pandas as pd
import tensorflow
import keras

In [26]:
df=pd.read_csv("Churn_Modelling.csv")

In [27]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [28]:
df=pd.get_dummies(columns=["Geography","Gender"],data=df)

In [29]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male
0,1,15634602,Hargrave,619,42,2,0.00,1,1,1,101348.88,1,True,False,False,True,False
1,2,15647311,Hill,608,41,1,83807.86,1,0,1,112542.58,0,False,False,True,True,False
2,3,15619304,Onio,502,42,8,159660.80,3,1,0,113931.57,1,True,False,False,True,False
3,4,15701354,Boni,699,39,1,0.00,2,0,0,93826.63,0,True,False,False,True,False
4,5,15737888,Mitchell,850,43,2,125510.82,1,1,1,79084.10,0,False,False,True,True,False

In [30]:
df.shape

(10000, 17)

In [31]:
df.isnull().sum()

RowNumber            0
CustomerId           0
Surname              0
CreditScore          0
Age                  0
Tenure               0
Balance              0
NumOfProducts        0
HasCrCard            0
IsActiveMember       0
EstimatedSalary      0
Exited               0
Geography_France     0
Geography_Germany    0
Geography_Spain      0
Gender_Female        0
Gender_Male          0
dtype: int64

In [32]:
df=df.drop(["RowNumber","CustomerId","Surname"],axis=1)

In [33]:
df.shape

(10000, 14)

In [34]:
X=df.drop("Exited",axis=1)
Y=df[["Exited"]]

In [35]:
from sklearn.model_selection import train_test_split

In [36]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=1)

In [37]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [38]:
model=Sequential()

In [39]:
model.add(Dense(units=6,kernel_initializer="uniform",activation="relu",input_dim=13))
model.add(Dense(units=6,kernel_initializer="uniform",activation="relu"))
model.add(Dense(units=1,kernel_initializer="uniform",activation="sigmoid"))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [40]:
model.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [41]:
model.fit(X_train,Y_train,batch_size=10,epochs=10,validation_split=0.1)

Epoch 1/10
630/630 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7892 - loss: 0.5921 - val_accuracy: 0.7800 - val_loss: 0.5365
Epoch 2/10
630/630 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7986 - loss: 0.5249 - val_accuracy: 0.7800 - val_loss: 0.5396
Epoch 3/10
630/630 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8050 - loss: 0.5063 - val_accuracy: 0.7800 - val_loss: 0.5310
Epoch 4/10
630/630 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7984 - loss: 0.5085 - val_accuracy: 0.7800 - val_loss: 0.5342
Epoch 5/10
630/630 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8070 - loss: 0.4958 - val_accuracy: 0.7800 - val_loss: 0.5232
Epoch 6/10
630/630 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7994 - loss: 0.5047 - val_accuracy: 0.7800 - val_loss: 0.5514
Epoch 7/10
630/630 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7949 - loss: 0.5102 - val_accuracy: 0.7800 - val_loss: 0.5220
Epoch 8/10
630/630 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7992 - loss: 0.4989 - val_accuracy: 0.7800 - val_loss: 0.5244
Epoch 9/10
630/630 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8051 - loss: 0.4915 - val_accuracy: 0.7800 - val_loss: 0.5230
Epoch 10/10
630/630 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8072 - loss: 0.4892 - val_accuracy: 0.7800 - val_loss: 0.5221

In [45]:
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.layers import Dropout

In [43]:
# Scale numerical features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Build deep learning model
model = Sequential([
    Dense(32, activation='relu', input_shape=(X_train.shape[1],)),
    Dropout(0.3),
    Dense(16, activation='relu'),
    Dropout(0.2),
    Dense(8, activation='relu'),
    Dense(1, activation='sigmoid')  # Output layer (binary classification)
])

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
epochs = 50
history = model.fit(X_train, Y_train, epochs=epochs, batch_size=32, validation_data=(X_test, Y_test))

Epoch 1/50

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

219/219 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7945 - loss: 0.5416 - val_accuracy: 0.7943 - val_loss: 0.4561
Epoch 2/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8069 - loss: 0.4591 - val_accuracy: 0.8137 - val_loss: 0.4323
Epoch 3/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8024 - loss: 0.4484 - val_accuracy: 0.8180 - val_loss: 0.4188
Epoch 4/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8178 - loss: 0.4261 - val_accuracy: 0.8220 - val_loss: 0.4127
Epoch 5/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8112 - loss: 0.4331 - val_accuracy: 0.8227 - val_loss: 0.4054
Epoch 6/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8213 - loss: 0.4137 - val_accuracy: 0.8250 - val_loss: 0.3979
Epoch 7/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8125 - loss: 0.4182 - val_accuracy: 0.8247 - val_loss: 0.3913
Epoch 8/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8178 - loss: 0.4111 - val_accuracy: 0.8263 - val_loss: 0.3870
Epoch 9/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8103 - loss: 0.4105 - val_accuracy: 0.8283 - val_loss: 0.3820
Epoch 10/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8154 - loss: 0.4069 - val_accuracy: 0.8293 - val_loss: 0.3784
Epoch 11/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8087 - loss: 0.3959 - val_accuracy: 0.8293 - val_loss: 0.3758
Epoch 12/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8285 - loss: 0.3871 - val_accuracy: 0.8293 - val_loss: 0.3738
Epoch 13/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8184 - loss: 0.3925 - val_accuracy: 0.8347 - val_loss: 0.3688
Epoch 14/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8310 - loss: 0.3825 - val_accuracy: 0.8557 - val_loss: 0.3675
Epoch 15/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8402 - loss: 0.3783 - val_accuracy: 0.8547 - val_loss: 0.3664
Epoch 16/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8472 - loss: 0.3728 - val_accuracy: 0.8593 - val_loss: 0.3631
Epoch 17/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8347 - loss: 0.3883 - val_accuracy: 0.8583 - val_loss: 0.3597
Epoch 18/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8448 - loss: 0.3647 - val_accuracy: 0.8617 - val_loss: 0.3550
Epoch 19/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8516 - loss: 0.3592 - val_accuracy: 0.8633 - val_loss: 0.3501
Epoch 20/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8453 - loss: 0.3710 - val_accuracy: 0.8637 - val_loss: 0.3478
Epoch 21/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8478 - loss: 0.3686 - val_accuracy: 0.8643 - val_loss: 0.3435
Epoch 22/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8545 - loss: 0.3532 - val_accuracy: 0.8653 - val_loss: 0.3441
Epoch 23/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8529 - loss: 0.3499 - val_accuracy: 0.8617 - val_loss: 0.3435
Epoch 24/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8580 - loss: 0.3447 - val_accuracy: 0.8630 - val_loss: 0.3441
Epoch 25/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8518 - loss: 0.3665 - val_accuracy: 0.8640 - val_loss: 0.3418
Epoch 26/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8498 - loss: 0.3572 - val_accuracy: 0.8620 - val_loss: 0.3417
Epoch 27/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8534 - loss: 0.3461 - val_accuracy: 0.8633 - val_loss: 0.3425
Epoch 28/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8581 - loss: 0.3507 - val_accuracy: 0.8617 - val_loss: 0.3417
Epoch 29/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8507 - loss: 0.3587 - val_accuracy: 0.8617 - val_loss: 0.3403
Epoch 30/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8489 - loss: 0.3700 - val_accuracy: 0.8613 - val_loss: 0.3398
Epoch 31/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8537 - loss: 0.3502 - val_accuracy: 0.8617 - val_loss: 0.3411
Epoch 32/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8533 - loss: 0.3550 - val_accuracy: 0.8600 - val_loss: 0.3399
Epoch 33/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8597 - loss: 0.3367 - val_accuracy: 0.8623 - val_loss: 0.3404
Epoch 34/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8593 - loss: 0.3557 - val_accuracy: 0.8633 - val_loss: 0.3382
Epoch 35/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8551 - loss: 0.3464 - val_accuracy: 0.8637 - val_loss: 0.3390
Epoch 36/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8533 - loss: 0.3517 - val_accuracy: 0.8627 - val_loss: 0.3407
Epoch 37/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8520 - loss: 0.3584 - val_accuracy: 0.8620 - val_loss: 0.3396
Epoch 38/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8560 - loss: 0.3570 - val_accuracy: 0.8630 - val_loss: 0.3399
Epoch 39/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8607 - loss: 0.3397 - val_accuracy: 0.8640 - val_loss: 0.3419
Epoch 40/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8639 - loss: 0.3341 - val_accuracy: 0.8637 - val_loss: 0.3415
Epoch 41/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8555 - loss: 0.3465 - val_accuracy: 0.8640 - val_loss: 0.3378
Epoch 42/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8591 - loss: 0.3356 - val_accuracy: 0.8650 - val_loss: 0.3373
Epoch 43/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8626 - loss: 0.3379 - val_accuracy: 0.8633 - val_loss: 0.3377
Epoch 44/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8594 - loss: 0.3360 - val_accuracy: 0.8643 - val_loss: 0.3401
Epoch 45/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8673 - loss: 0.3377 - val_accuracy: 0.8650 - val_loss: 0.3383
Epoch 46/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8644 - loss: 0.3460 - val_accuracy: 0.8623 - val_loss: 0.3371
Epoch 47/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8558 - loss: 0.3450 - val_accuracy: 0.8650 - val_loss: 0.3379
Epoch 48/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8662 - loss: 0.3314 - val_accuracy: 0.8613 - val_loss: 0.3375
Epoch 49/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8584 - loss: 0.3432 - val_accuracy: 0.8627 - val_loss: 0.3381
Epoch 50/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8621 - loss: 0.3406 - val_accuracy: 0.8617 - val_loss: 0.3380

In [44]:
# Evaluate performance
loss, accuracy = model.evaluate(X_test, Y_test)
print(f"Test Accuracy: {accuracy:.2f}")

94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8652 - loss: 0.3385
Test Accuracy: 0.86